version: "3"

services:
  database:
    image: postgres:14.6
    container_name: sync-poc
    ports:
      - 5555:5432
    volumes:
      - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    environment:
      - POSTGRES_HOST=test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
